function gf = reset_gf(gf)

names = fieldnames(gf);

to_keep = {'home_dir',...
            'directory',...
            'weight_dir',...
            'save_dir',...
            'tank_parent',...
            'calibDir',...
            'defaultPaths',...
            'recFerrets',...
            'stimDevice',...
            'recDevice',...
            'trackFerrets',...
            'split_screen_video',...
            'high_res_video'};
        
        
for i = 1 : numel(names)
    if ~any( strcmp(to_keep, names{i}))        
        gf = rmfield(gf, names{i});
    end   
end